language: node_js
node_js:
  - 13

services:
  - docker

before_install:
  - docker --version # print the version for logging
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker build -t ctala/udagram-api .
  - docker push ctala/udagram-api:latest

# safelist
branches:
  only:
  - master